### get test
GET http://localhost:3000

### get method
GET http://localhost:3000/api/persons/
version: 2.0

### post method
POST http://localhost:3000/api/persons/ HTTP/1.1
content-type: application/json
version: 1.2

{
    "nationality": "japan", 
    "firstName": "kazu", 
    "lastName": "kamai",
    "city": "kyoto",
    "occupation" : "doctor"
}

### put method, need ID to specify data
PUT http://localhost:3000/api/persons/3 HTTP/1.1
content-type: application/json
version: 1.2

{
    "nationality" : "india",
    "lastName": "dori"
}

### delete method, need ID to specify data
DELETE http://localhost:3000/api/persons/3 HTTP/1.1


### get method
GET http://localhost:3000/api/persons/3
version: 2.0

### search method
GET http://localhost:3000/api/persons/japan/kazu/kamai/kyoto/creator